### ISSUE TITLE
Newest commit has issues with bs4

### ISSUE THREAD

**Issue by k-e-l-p** [FrozenPigs/Taigabot#22] opened 2020-05-02 21:38 UTC
All libraries were installed via `$pip2 install -r requirements.txt`
Seems to have something to do with the beautifulsoup4 library
I am reverting the bot on the server to an older commit as a temporary workaround.
hmu when yall properly test and fix it

Here's a full traceback:
```
UguuBot DEV (Development) <http://github.com/infinitylabs/UguuBot>
Operating System: Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic, Python Version: CPython 2.7.17, Architecture: 64bit 
Loading plugins...
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/youtube.py", line 6, in <module>
    from util import hook, http, timeformat
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 306, in <module>
    from . import _html5lib
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/twitch.py", line 4, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/stupid.py", line 1, in <module>
    from util import hook,http, database
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/debt.py", line 1, in <module>
    from util import hook, http, text, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/fact.py", line 1, in <module>
    from util import hook, http, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/calculator.py", line 5, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/furry.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/distro.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/media.py", line 3, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/utility.py", line 6, in <module>
    from util import hook, http, text, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/urls.py", line 11, in <module>
    import gelbooru
  File "plugins/gelbooru.py", line 1, in <module>
    from util import hook, http, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/newegg.py", line 1, in <module>
    from util import hook, http, text, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/coins.py", line 1, in <module>
    from util import http, hook
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/lastfm.py", line 1, in <module>
    from util import hook, http, database
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/duckduckgo.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/hashtags.py", line 2, in <module>
    from util import hook, http, text, execute, database
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/core_user.py", line 1, in <module>
    from util import hook, database, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/weather.py", line 1, in <module>
    from util import hook, http, web, database
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/wolframalpha.py", line 3, in <module>
    from util import hook, http, text, web, formatting
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/amazon.py", line 1, in <module>
    from util import hook, http, text, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/vimeo.py", line 1, in <module>
    from util import hook, http, timeformat
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/answers.py", line 1, in <module>
    from util import hook, web, text
  File "plugins/util/web.py", line 3, in <module>
    import http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/mygengo_translate.py", line 3, in <module>
    from util import http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/fmylife.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/anime.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/stock.py", line 1, in <module>
    from util import hook, web
  File "plugins/util/web.py", line 3, in <module>
    import http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/lyrics.py", line 1, in <module>
    from util import hook, http, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/spotify.py", line 3, in <module>
    from util import hook, http, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/dictionary.py", line 4, in <module>
    from util import http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/steam.py", line 2, in <module>
    from util import hook, http, web, text
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/yandere.py", line 1, in <module>
    from util import hook, http, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/help.py", line 3, in <module>
    from util import hook, user, web
  File "plugins/util/web.py", line 3, in <module>
    import http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/soundcloud.py", line 1, in <module>
    from util import hook, http, web, text
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/translate.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/4chan.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/domains.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/religion.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/drama.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/distance.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/radio.py", line 2, in <module>
    from util import hook, http, web, text
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/validate.py", line 7, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/urban.py", line 1, in <module>
    from util import hook, http, text
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/metacritic.py", line 6, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/bash.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/google.py", line 1, in <module>
    from util import hook, http, database, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/pomf.py", line 12, in <module>
    import hashtags, datafiles
  File "plugins/hashtags.py", line 2, in <module>
    from util import hook, http, text, execute, database
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/snopes.py", line 3, in <module>
    from util import hook, http, formatting
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/kernel.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/gainz.py", line 1, in <module>
    from util import hook, database, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/rss.py", line 1, in <module>
    from util import hook, http, web, text
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/gelbooru.py", line 1, in <module>
    from util import hook, http, web
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/mylifeisaverage.py", line 1, in <module>
    from util import hook, http
  File "plugins/util/http.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/home/taigabot/.local/lib/python2.7/site-packages/bs4/builder/__init__.py", line 303, in <module>
    from . import _htmlparser
ImportError: cannot import name _htmlparser

```

**Comment by k-e-l-p** [comment] 2020-05-02 21:46
Update: rolling back to commit `205a9d9` didn't do anything. So my next suspicion is the bs4 library being screwed up somehow

**Comment by k-e-l-p** [comment] 2020-05-02 22:00
My suspicion was correct: Updating the bs4 library to the newest current release (`4.9.0`) fixed the issue. Please update `requirements.txt` to reflect the change as i am too lazy to PR

**Comment by ineeee** [comment] 2020-05-03 11:32
thanks for posting such an insightful log, those 640 lines of the same error _really_ add to the issue.

the commit where i started documenting the used libraries is b25904f7d91b0337a280f3bf0f83e7fc3a97b7d8, this change only adds a markdown file with details. one can browse the repo at this point--previous to any changes-- and see that taiga uses bs4 4.1.3, as shown in line 20 of `__init__.py` [here](https://github.com/FrozenPigs/Taigabot/blob/b25904f7d91b0337a280f3bf0f83e7fc3a97b7d8/lib/bs4/__init__.py#L20):

    __author__ = "Leonard Richardson (leonardr@segfault.org)"
    __version__ = "4.1.3"
    __copyright__ = "Copyright (c) 2004-2012 Leonard Richardson"
    __license__ = "MIT"

the version i've added to `requirements.txt` in commit a05a38da9cb6d617fed7a481e9198e12b53e8644 (which replaces vendorized libs with pip's) is exactly the same, as can be seen on the file [here](https://github.com/FrozenPigs/Taigabot/blob/a05a38da9cb6d617fed7a481e9198e12b53e8644/requirements.txt#L3) in line 3:

    httplib2==0.7.5
    BeautifulSoup4==4.1.3
    lxml==3.3.6

as i was unable to reproduce this issue, i conclude the following:
- it is an issue with your specific instance of taigabot, or
- taigabot's bundled bs4 had some unknown modifications which i'm not aware of because it didn't error out while i was testing

i vote for the last one, since `oauth2` and `yql` are modified (differ from the same version in pip).

**Comment by k-e-l-p** [comment] 2020-05-03 11:41
I am not here to discuss when or why was the bug introduced.
The problem right now is that the specific version of bs4 that is being used in the repository was causing undefined behaviour, updating the library seemed to fix it in my case without introducing any new bugs. If you aren't willing to comply with any of the solutions I can provide to whatever technical issues arise then don't complain to me about downtime.

**Comment by ineeee** [comment] 2020-05-03 11:42
lol

fixed in https://github.com/FrozenPigs/Taigabot/pull/24

**Closed as completed** 2020-05-04 10:06 UTC
